{"title": ["JavaScript Essentials"], "link": ["http://www.techotopia.com/index.php/JavaScript_Essentials"], "desc": ["An online book designed to teach web designers to develop dynamic and interactive web pages using the language.\r"]}
{"title": ["Joy of JavaScript"], "link": ["http://www.chalcedony.com/javascript/"], "desc": ["The accompanying web site to the book \"JavaScript   for the World Wide Web, Visual QuickStart Guide,  4th Edition,\" by Tom Negrino and Dori Smith.  Includes all the scripts in the book.\r"]}
{"title": ["Professional JavaScript"], "link": ["http://www.webreference.com/programming/javascript/professional/"], "desc": ["A large, detailed, and compendius book covering JavaScript from many angles: browser, server, standalone and embedded. Explains interworking with Java, DHTML, ASP, WSH, CGI, cookies and others. Numerous complete examples.\r"]}
{"title": ["Core Python Programming"], "link": ["http://www.pearsonhighered.com/educator/academic/product/0,,0130260363,00%2Ben-USS_01DBC.html"], "desc": ["By Wesley J. Chun; Prentice Hall PTR, 2001, ISBN 0130260363. For experienced developers to improve extant skills; professional level examples. Starts by introducing syntax, objects, error handling, functions, classes, built-ins. [Prentice Hall]\r"]}
{"title": ["Data Structures and Algorithms with Object-Oriented Design Patterns in Python"], "link": ["http://www.brpreiss.com/books/opus7/html/book.html"], "desc": ["The primary goal of this book is to promote object-oriented design using Python and to illustrate the use of the emerging object-oriented design patterns.\r"]}
{"title": ["Dive Into Python 3"], "link": ["http://www.diveintopython.net/"], "desc": ["By Mark Pilgrim, Guide to Python 3  and its differences from Python 2. Each chapter starts with a real code sample and explains it fully. Has a comprehensive appendix of all the syntactic and semantic changes in Python 3\r"]}
{"title": ["Foundations of Python Network Programming"], "link": ["http://rhodesmill.org/brandon/2011/foundations-of-python-network-programming/"], "desc": ["This book covers a wide range of topics. From raw TCP and UDP to encryption with TSL, and then to HTTP, SMTP, POP, IMAP, and ssh. It gives you a good understanding of each field and how to do everything on the network with Python.\r"]}
{"title": ["Free Python books"], "link": ["http://www.techbooksforfree.com/perlpython.shtml"], "desc": ["Free Python books and tutorials.\r"]}
{"title": ["FreeTechBooks: Python Scripting Language"], "link": ["http://www.freetechbooks.com/python-f6.html"], "desc": ["Annotated list of free online books on Python scripting language. Topics range from beginner to advanced.\r"]}
{"title": ["How to Think Like a Computer Scientist: Learning with Python"], "link": ["http://greenteapress.com/thinkpython/"], "desc": ["By Allen B. Downey, Jeffrey Elkner, Chris Meyers; Green Tea Press, 2002, ISBN 0971677506. Teaches general principles of programming, via Python as subject language. Thorough, in-depth approach to many basic and intermediate programming topics. Full text online and downloads: HTML, PDF, PS, LaTeX. [Free, Green Tea Press]\r"]}
{"title": ["An Introduction to Python"], "link": ["http://www.network-theory.co.uk/python/intro/"], "desc": ["By Guido van Rossum, Fred L. Drake, Jr.; Network Theory Ltd., 2003, ISBN 0954161769. Printed edition of official tutorial, for v2.x, from Python.org. [Network Theory, online]\r"]}
{"title": ["Learn to Program Using Python"], "link": ["http://www.freenetpages.co.uk/hp/alan.gauld/"], "desc": ["Book by Alan Gauld with full text online. Introduction for those learning programming basics: terminology, concepts, methods to write code. Assumes no prior knowledge but basic computer skills.\r"]}
{"title": ["Making Use of Python"], "link": ["http://www.wiley.com/WileyCDA/WileyTitle/productCd-0471219754.html"], "desc": ["By Rashi Gupta; John Wiley and Sons, 2002, ISBN 0471219754. Covers language basics, use for CGI scripting, GUI development, network programming; shows why it is one of more sophisticated of popular scripting languages. [Wiley]\r"]}
{"title": ["Practical Python"], "link": ["http://hetland.org/writing/practical-python/"], "desc": ["By Magnus Lie Hetland; Apress LP, 2002, ISBN 1590590066. Readable guide to ideas most vital to new users, from basics common to high level languages, to more specific aspects, to a series of 10 ever more complex programs. [Apress]\r"]}
{"title": ["Pro Python System Administration"], "link": ["http://www.sysadminpy.com/"], "desc": ["By Rytis Sileika, ISBN13: 978-1-4302-2605-5,  Uses real-world system administration examples like manage devices with SNMP and SOAP, build a distributed monitoring system, manage web applications and parse complex log files, monitor and manage MySQL databases.\r"]}
{"title": ["Programming in Python 3 (Second Edition)"], "link": ["http://www.qtrac.eu/py3book.html"], "desc": ["A Complete Introduction to the Python 3.\r"]}
{"title": ["Python 2.1 Bible"], "link": ["http://www.wiley.com/WileyCDA/WileyTitle/productCd-0764548077.html"], "desc": ["By Dave Brueck, Stephen Tanner; John Wiley and Sons, 2001, ISBN 0764548077. Full coverage, clear explanations, hands-on examples, full language reference; shows step by step how to use components, assemble them, form full-featured programs. [John Wiley and Sons]\r"]}
{"title": ["Python 3 Object Oriented Programming"], "link": ["https://www.packtpub.com/python-3-object-oriented-programming/book"], "desc": ["A step-by-step tutorial for OOP in Python 3, including discussion and examples of abstraction, encapsulation, information hiding, and raise, handle, define, and manipulate exceptions.\r"]}
{"title": ["eff-bot's Daily Python URL"], "link": ["http://www.pythonware.com/daily/"], "desc": ["Contains links to assorted resources from the Python universe, compiled by PythonWare.\r"]}
{"title": ["Free Python and Zope Hosting Directory"], "link": ["http://www.oinko.net/freepython/"], "desc": ["A directory of free Python and Zope hosting providers, with reviews and ratings.\r"]}
{"title": ["O'Reilly Python Center"], "link": ["http://oreilly.com/python/"], "desc": ["Features Python books, resources, news and articles.\r"]}
{"title": ["Python Developer's Guide"], "link": ["http://www.python.org/dev/"], "desc": ["Resources for reporting bugs, accessing the Python source tree with CVS and taking part in the development of Python.\r"]}
{"title": ["Social Bug"], "link": ["http://win32com.goermezer.de/"], "desc": ["Scripts, examples and news about Python programming for the Windows platform.\r"]}
{"title": ["Python Language Reference Manual"], "link": ["http://www.network-theory.co.uk/python/language/"], "desc": ["By Guido van Rossum, Fred L. Drake, Jr.; Network Theory Ltd., 2003, ISBN 0954161785. Printed edition of official language reference, for v2.x, from Python.org, describes syntax, built-in datatypes. [Network Theory, online]\r"]}
{"title": ["Python Programming Patterns"], "link": ["http://www.pearsonhighered.com/educator/academic/product/0,,0130409561,00%2Ben-USS_01DBC.html"], "desc": ["By Thomas W. Christopher; Prentice Hall PTR, 2002, ISBN 0130409561. Shows how to write large programs, introduces powerful design patterns that deliver high levels of robustness, scalability, reuse.\r"]}
{"title": ["Python Programming with the Java Class Libraries: A Tutorial for Building Web and Enterprise Applications with Jython"], "link": ["http://www.informit.com/store/product.aspx?isbn=0201616165&redir=1"], "desc": ["By Richard Hightower; Addison-Wesley, 2002, 0201616165. Begins with Python basics, many exercises, interactive sessions. Shows programming novices concepts and practical methods. Shows programming experts Python's abilities and ways to interface with Java APIs. [publisher website]\r"]}
{"title": ["Python: Visual QuickStart Guide"], "link": ["http://www.pearsonhighered.com/educator/academic/product/0,,0201748843,00%2Ben-USS_01DBC.html"], "desc": ["By Chris Fehily; Peachpit Press, 2002, ISBN 0201748843. Task-based, step-by-step visual reference guide, many screen shots, for courses in digital graphics; Web design, scripting, development; multimedia, page layout, office tools, operating systems. [Prentice Hall]\r"]}
{"title": ["Sams Teach Yourself Python in 24 Hours"], "link": ["http://www.informit.com/store/product.aspx?isbn=0672317354"], "desc": ["By Ivan Van Laningham; Sams Publishing, 2000, ISBN 0672317354. Split into 24 hands-on, 1 hour lessons; steps needed to learn topic: syntax, language features, OO design and programming, GUIs (Tkinter), system administration, CGI. [Sams Publishing]\r"]}
{"title": ["Text Processing in Python"], "link": ["http://gnosis.cx/TPiP/"], "desc": ["By David Mertz; Addison Wesley. Book in progress, full text, ASCII format. Asks for feedback. [author website, Gnosis Software, Inc.]\r"]}
{"title": ["XML Processing with Python"], "link": ["http://www.informit.com/store/product.aspx?isbn=0130211192"], "desc": ["By Sean McGrath; Prentice Hall PTR, 2000, ISBN 0130211192, has CD-ROM. Methods to build XML applications fast, Python tutorial, DOM and SAX, new Pyxie open source XML processing library. [Prentice Hall PTR]\r"]}
{"title": ["1StopPopup's JavaScript Popup Creator"], "link": ["http://1stoppopup.com/"], "desc": ["Makes JavaScript popup window code.\r"]}
{"title": ["4 Colors Selector"], "link": ["http://www.stormloader.com/4colors/"], "desc": ["A JavaScript color picker.\r"]}
{"title": ["Aarons ScriptCalendar"], "link": ["http://www.scriptcalendar.com/"], "desc": ["An event driven DHTML JavaScript Calendar that displays dates and events in typical wall calendar format.\r"]}
{"title": ["Arun's Javascript Utilities"], "link": ["http://jsutils.sourceforge.net/"], "desc": ["Collection of ready-to-use Javascripts, features a flexible Javascript PopUp Calendar, PopCal.\r"]}
{"title": ["Bmgadg.com"], "link": ["http://bmgadg.com/javascript.php"], "desc": ["Javascripts for form validation, browser detection, cookies, images swaping. Also calculator and slider game.\r"]}
{"title": ["Bretteleben.de"], "link": ["http://www.bretteleben.de/"], "desc": ["A small collection of free javascripts, created by the website-owner, mostly about image-presentation and image-manipulation, presented in german and english. The scripts are crossbrowser, one or two of them (one more way, rotating globe) unique at this time.\r"]}
{"title": ["Canvas Clocks"], "link": ["http://perisic.com/canvasclock/"], "desc": ["Provides a clock using the WHATWG <canvas> element.\r"]}
{"title": ["Cerny"], "link": ["http://www.cerny-online.com/cerny.js/"], "desc": ["Offers solutions for type checking, schema validation and dependency management.\r"]}
{"title": ["ColorPop"], "link": ["http://www.iconico.com/colorPop/"], "desc": ["A pop-up color picker control for use on web pages.\r"]}
{"title": ["Cory's Javascript Page"], "link": ["http://www.angelfire.com/scifi/vykk/"], "desc": ["Offers a number of basic scripts.\r"]}
{"title": ["Custom Form Elements with Javascript"], "link": ["http://customformelements.net/"], "desc": ["An open source library to enhance web-based XHTML forms in terms of style, usability and accessibility by using Javascript and CSS. It is based on various Javascript frameworks. Features, demo, download, how-tos, and inside information on the development team are presented,\r"]}
{"title": ["DHTML Cross-Browser JavaScripts"], "link": ["http://vbarsan.com/"], "desc": ["Vertical, horizontal and typewriter scrollers, and a collection of free Javascripts. Multi-OS and multi-browser compatible.\r"]}
{"title": ["Editable JavaScript TreeGrid"], "link": ["http://www.coqsoft.com/"], "desc": ["DHTML component written in pure JavaScript to display and edit data in table, grid, tree or grid with tree. Compatible with the most of standard browsers. ASP.NET support code available. [Commercial]\r"]}
{"title": ["Email AntiLeech"], "link": ["http://www.artatoo.com/scripts/email_antileech.shtml"], "desc": ["Prevents all software to grab email addresses from site.\r"]}
{"title": ["ESPX  and TinyXSL"], "link": ["http://www.cjandia.com/2001/espx-tinyxsl/"], "desc": ["ESPX, an ECMAScript Parser for (almost) XML, with namespaces; and TinyXSL, XML transform in-Script mini-Language\r"]}
{"title": ["FCKeditor"], "link": ["http://www.fckeditor.net/"], "desc": ["Web-based HTML text editor with powerful formatting capabilities. Requires no installation on the client computer.\r"]}
{"title": ["Focus on JavaScript"], "link": ["http://javascript.about.com/"], "desc": ["A bulk of scripts and other JavaScript resources.\r"]}
{"title": ["GEEKO CMS"], "link": ["http://www.cms.online-business.ro/"], "desc": ["A JavaScript based content management system. Site content generated at client side by simple text files which can be changed in a text editor. [Free]\r"]}
{"title": ["HIOX Free Javascript Scripts"], "link": ["http://hscripts.com/scripts/JavaScript/"], "desc": ["Free Javascript scripts includes stop watch, timer, domain and email validation script, date functions, alphanumeric validation function.\r"]}
{"title": ["HTML2XHTML Converter (H2X)"], "link": ["http://html2xhtml.richarea.com/"], "desc": ["Generates a well-formed XHTML string from an HTML DOM object. H2X could be used in Content Management Systems (CMS), online wysiwyg HTML editors or any other javascript application to produce well formed XHTML 1.0 code.\r"]}
{"title": ["I-Announce"], "link": ["http://www.i-announce.net/"], "desc": ["Add javascript Popups Announcements to website. Popup content can be easily changed by the website owner - from the Popup itself. Requires registration (Free) and easy install code.\r"]}
{"title": ["Inc"], "link": ["http://johannburkard.de/blog/programming/javascript/inc-a-super-tiny-client-side-include-javascript-jquery-plugin.html"], "desc": ["Provides a JQuery plugin to include files in a web page.\r"]}
{"title": ["JavaScript Diagram Builder"], "link": ["http://www.lutanho.net/diagram/"], "desc": ["Library of objects and functions, to display and dynamically modify coordinate diagrams and charts in webpages. [Freeware]\r"]}
{"title": ["JavaScript Photo Album"], "link": ["http://www.kitykity.com/photoalbum/"], "desc": ["JavaScript to display photo albums with many customizable options.\r"]}
{"title": ["JavaScript Scrambler"], "link": ["http://www.tero.co.uk/scripts/scrambler.php"], "desc": ["Script for converting your JavaScripts into difficult to read JavaScripts\r"]}
{"title": ["JavaScript Shell"], "link": ["http://www.squarefree.com/shell/"], "desc": ["A read-eval-print loop for JavaScript that works in IE, Mozilla, and Opera.  Includes a Mozilla bookmarklet to run shell commands in the context of any web page.\r"]}
{"title": ["JavaScript Spin Control"], "link": ["http://www.ycode.com/Spin/Latest/Spin.htm"], "desc": ["Like a regular Windows Spin control, but is implemented entirely in JavaScript. [Commercial]\r"]}
{"title": ["JavaScript Ticker"], "link": ["http://www.jsticker.com/"], "desc": ["Collection of tickers for simple text, RSS news and stock market quotes. [Commercial]\r"]}
{"title": ["JSCart Shopping Cart"], "link": ["http://www.cnctek.com/JSCart/"], "desc": ["Javascript shopping cart capable to support thousands of products through a powerful database manager. [Commercial]\r"]}
{"title": ["JSMIN, The JavaScript Minifier"], "link": ["http://www.crockford.com/javascript/jsmin.html"], "desc": ["Provides a script to remove comments and unnecessary whitespaces from JavaScript files.\r"]}
{"title": ["JSviewer"], "link": ["http://www.jsviewer.com/"], "desc": ["A configurable dynamic HTML image and slide show viewer written in JavaScript. Supports displaying images, web pages and text. Supports keyboard controls and multiple languages.\r"]}
{"title": ["Magic Toolbox"], "link": ["http://www.magictoolbox.com/"], "desc": ["Provides an image zoom script in two different versions. [Commercial]\r"]}
{"title": ["markItUp"], "link": ["http://markitup.jaysalvat.com/"], "desc": ["Offers a jquery plugin to turn textareas to markup editors with the support of HTML, Textile, Wiki Syntax, Markdown and BBCode.\r"]}
{"title": ["Modernizr"], "link": ["http://www.modernizr.com/"], "desc": ["A JavaScript toolkit that allows web developers to use new CSS3 and HTML5 features while maintaining a fine level of control over browsers that don't support them yet.\r"]}
{"title": ["Pop Up Window Generator"], "link": ["http://www.a1ien51.8k.com/scripts/popupwingenV2.htm"], "desc": ["Online pop up generator. Free and highly customizable.\r"]}
{"title": ["PopCalendarXP And FlatCalendarXP"], "link": ["http://www.calendarxp.net/"], "desc": ["The javascript calendar with themes support. [Freeware and Commercial]\r"]}
{"title": ["Prototip"], "link": ["http://www.nickstakenburg.com/projects/prototip/"], "desc": ["Allows to create simple and complex tooltips with the Prototype framework and to emphasize them with Script.aculo.us.\r"]}
{"title": ["qForms"], "link": ["http://www.pengoworks.com/index.cfm?action=qForms"], "desc": ["JavaScript API for interfacing forms. [Open source, GPL]\r"]}
{"title": ["Rectangular Marquee Tool"], "link": ["http://marqueetool.net/"], "desc": ["Javascript object allowing to select rectangular areas on <DIV> or <IMG> elements. [Free]\r"]}
{"title": ["Regular Expression Tester"], "link": ["http://www.roblocher.com/technotes/regexp.aspx"], "desc": ["Uses browser's JavaScript to show matches and subgroups, and highlights match in the input string.\r"]}
{"title": ["RGraph"], "link": ["http://www.rgraph.net/"], "desc": ["A graphing library for websites on all platforms. Includes stable/beta download, working examples, and details of the benefits of using the HTML5's canvas element.\r"]}
{"title": ["Search Maker Pro"], "link": ["http://www.searchmakerpro.com/"], "desc": ["Allows to create a web page that includes a search engine.  The code can be placed on the website to enable a site search.\r"]}
{"title": ["Send A Link"], "link": ["http://www.send-a-link.com/"], "desc": ["JavaScript tools that enable your web page visitors to bookmark your site, send an email about it to a friend, or make it their homepage, or with a single mouse click.\r"]}
{"title": ["Snow"], "link": ["http://www.altan.hr/snow/"], "desc": ["Makes it look like snow is falling down the screen. [Freeware]\r"]}
{"title": ["Tigra Color Picker"], "link": ["http://www.softcomplex.com/products/tigra_color_picker/"], "desc": ["Makes easy for visitors to fill out color value field(s) by selecting the color from a popup palette. [Freeware]\r"]}
{"title": ["Tigra Form Validator"], "link": ["http://www.softcomplex.com/products/tigra_form_validator/"], "desc": ["A free JavaScript component performing client side form validation.\r"]}
{"title": ["Tigra Form Validator PRO"], "link": ["http://www.softcomplex.com/products/tigra_form_validator_pro/"], "desc": ["A JavaScript component performing client-side form validation.\r"]}
{"title": ["Tigra Hints"], "link": ["http://www.softcomplex.com/products/tigra_hints/"], "desc": ["Displays pop-up box with notes (also known as tooltips or hints) when mouse appears over any HTML element on the page. [Freeware]\r"]}
{"title": ["Tigra Scroller"], "link": ["http://www.softcomplex.com/products/tigra_scroller/"], "desc": ["Scrolls text or html in the box. [Freeware]\r"]}
{"title": ["Tipue"], "link": ["http://www.tipue.com/"], "desc": ["A JavaScript site search engine. It works with any browser that supports JavaScript 1.3 and at least partially supports the W3C DOM Level 1. [Open source, GPL]\r"]}
{"title": ["Xmenu-xlayer"], "link": ["http://xmenu-xlayer.sourceforge.net/"], "desc": ["A versatile, Javascript driven DHTML menu that works on most popular browsers. It comes in 3 basic modes: vertical, horizontal or collapsing and folds/unfolds on clicks or mouseovers. [Open source, LGPL]\r"]}
{"title": ["XSLT JS"], "link": ["http://johannburkard.de/software/xsltjs/"], "desc": ["Tiny library for client-side (browser) transformations of XML with XSLT.\r"]}
{"title": ["Yav"], "link": ["http://yav.sourceforge.net/"], "desc": ["A Javascript-based form validation script supporting advanced features. [Open source, LGPL]\r"]}
{"title": ["yCode"], "link": ["http://www.ycode.com/"], "desc": ["Proposes JavaScript/DHTML controls to extend existing HTML control set including ComboBox, SpreadSheet, Spin, Scrambler. [Commercial]\r"]}
